language: node_js
node_js: "stable"

# cache some files for faster builds
cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

# Add global environment
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

# Locate the app folder
before_install:
  - cd app
  - apt-get install rpm

# Making the build process parallel: one on mac and one on linux
jobs:
  include:
    - os: osx
      osx_image: xcode10.2
      script:
        - yarn release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine

    - os: linux
      dist: xenial
      script:
        - yarn release

deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: true

# only run this script on pull requests and merges into
# the 'master' branches
branches:
  only:
    - master
