language: node_js
node_js:
  - "lts/*"

# cache some files for faster builds
cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

# Add global environment
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

# Making the build process parallel: one on mac and one on linux
jobs:
  include:
    - if: tag IS present
      os: osx
      osx_image: xcode11.1
      before_install:
        - cd app
      script:
        - yarn release --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine

    - if: tag IS present
      os: linux
      dist: xenial
      before_install:
        - sudo apt-get install rpm
        - cd app
        - rm -r yarn.lock
      # Make apt-get update automatically on every build
      # https://docs.travis-ci.com/user/installing-dependencies/
      addons:
        apt:
          update: true
      script:
        - yarn release

deploy:
  provider: releases
  token: $GH_TOKEN
  overwrite: true
  cleanup: true
  on:
    tags: true
    branch: master
  edge: true
