language: node_js
node_js: "stable"

# cache some files for faster builds
cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

# Add global environment
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

# Locate the app folder
before_install:
  - cd app
  - sudo snap install snapcraft --classic

jobs:
  include:
    - stage: Test
      script:
        - yarn test

    - os: osx
      osx_image: xcode10.2

    - os: linux
      dist: xenial

# only deploy to github on a merge to the development branch
deploy:
  provider: script
  script: bash deploy.travis.sh
  cleanup: true
  on:
    branch: development

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

# only run this script on pull requests and merges into
# the 'master' and 'development' branches
branches:
  only:
    - master
    - development
